title: Guillaume Zahnd
description: Homepage
url: "https://guillaumezahnd.github.io"
baseurl: ""

remote_theme: just-the-docs/just-the-docs

markdown: kramdown
kramdown:
  math_engine: mathjax

plugins:
  - jekyll-remote-theme
  - jekyll-github-metadata
  
custom_css: assets/css/custom.css  

callouts_level: quiet
callouts:
  note:
      title: Note
      color: blue
  tip:
      title: Tip
      color: green
  warning:
      title: Warning
      color: yellow
  important:
      title: Important
      color: purple
  caution:
      title: Caution
      color: red
